from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
import random
from faker import Faker
fake = Faker()
random_email = fake.email()


def test_registerUser():
    driver = webdriver.Chrome()
    driver.implicitly_wait(3)
    driver.get("https://www.automationexercise.com/")
    print("title is: " + driver.title)
    sign_loginbtn = driver.find_element(By.PARTIAL_LINK_TEXT, "Signup / Login")
    sign_loginbtn.click()

    sign_login_page = driver.find_element(By.XPATH, "//h2[text()='New User Signup!']")
    print("singup form heading is: ", sign_login_page.text)
    assert sign_login_page.text == "New User Signup!"
    name = driver.find_element(By.CSS_SELECTOR, '[data-qa="signup-name"]')
    name.send_keys("testing_selenium")
    email = driver.find_element(By.CSS_SELECTOR, '[data-qa="signup-email"]')
    email.send_keys(random_email + Keys.RETURN)
    print("email is : ", random_email)
    female_rdBtn = driver.find_element(By.ID, "id_gender1")
    male_rdBtn = driver.find_element(By.ID, "id_gender2")
    print("female radio button is not selected: ", not female_rdBtn.is_selected())
    print("male radio button is not selected: ", not male_rdBtn.is_selected())
    male_rdBtn.click()
    print("female radio button is selected: ", female_rdBtn.is_selected())
    print("male radio button is selected: ", male_rdBtn.is_selected())
    password = driver.find_element(By.ID, "password")
    password.send_keys("selenium123")
    date = driver.find_element(By.ID, "days")
    select_date = Select(date)
    select_date.select_by_value("5")
    months = driver.find_element(By.ID, "months")
    select_month = Select(months)
    select_month.select_by_visible_text("April")
    years = driver.find_element(By.ID, "years")
    select_years = Select(years)
    select_years.select_by_visible_text("2008")
    newsletter = driver.find_element(By.ID, "newsletter")
    newsletter.click()
    Fname = driver.find_element(By.ID, "first_name")
    Fname.send_keys("selenium")
    Lname = driver.find_element(By.ID, "last_name")
    Lname.send_keys("python")
    address = driver.find_element(By.ID, "address1")
    address.send_keys("St # 303 SanFranc")
    country = driver.find_element(By.ID, "country")
    select_country = Select(country)
    select_country.select_by_value("United States")
    state = driver.find_element(By.ID, "state")
    state.send_keys("Alaska")
    city = driver.find_element(By.ID, "city")
    city.send_keys("Anchorage")
    zipcode = driver.find_element(By.ID, "zipcode")
    zipcode.send_keys("99599")
    mobile_no = driver.find_element(By.ID, "mobile_number")
    mobile_no.send_keys("907-250-6652")
    submit_button = driver.find_element(By.CSS_SELECTOR, '[data-qa="create-account"]')
    submit_button.click()
    account_created = driver.find_element(By.XPATH, '//b[text()="Account Created!"]')
    print(account_created.text)
    assert account_created.text == "ACCOUNT CREATED!"
    driver.quit()

def test_validceredetialslogin():
    driver = webdriver.Chrome()
    driver.implicitly_wait(3)
    driver.get("https://www.automationexercise.com/")
    sign_loginbtn = driver.find_element(By.PARTIAL_LINK_TEXT, "Signup / Login")
    sign_loginbtn.click()
    login_email = driver.find_element(By.CSS_SELECTOR, '[data-qa="login-email"]')
    login_email.send_keys("carrolljennifer@example.org")
    loginpassword = driver.find_element(By.CSS_SELECTOR, '[data-qa="login-password"]')
    loginpassword.send_keys("selenium123"+ Keys.RETURN)
    loggedin_title = driver.find_element(By.TAG_NAME, "b")
    print("login title is : ", loggedin_title.text)
    driver.quit()